// lib/importGuideText.ts
//
// Parses a plain-text "guide template" (written by hand, or generated by
// an LLM from the prompt in GUIDE_IMPORT_PROMPT) into the same shape the
// admin How-To editor's React state uses. This lets an entire article —
// title, meta, intro, steps, sections, FAQs, and references — be pasted
// in and applied in one shot instead of being typed field-by-field.
//
// Template format (each block starts at the beginning of a line):
//
//   # TITLE
//   How To Start a Poultry Farming Business In Kenya
//
//   # META
//   Meta Title: ...
//   Meta Description: ...
//   Keywords: a, b, c
//
//   # INTRO
//   Intro body in RichTextEditor markdown (**bold**, [1] citations, etc.)
//
//   # STEP
//   Step Title
//   Image: https://... (optional, must be its own line right after the title)
//   Step body in RichTextEditor markdown…
//
//   # SECTION TIPS: Optional Title
//   Section body…
//   (type is one of TIPS | WARNING | NOTE | INFO | CONCLUSION; title after
//   the colon is optional — CONCLUSION sections often have none)
//
//   # FAQ
//   Question line
//   Answer body…
//
//   # REFERENCE 1
//   Title: Source Title
//   URL: https://source-url.com
//
// Everything after a directive line, up to the next directive, is that
// block's body. Blocks can appear in any order and repeat freely.

export type SectionType = 'TIPS' | 'WARNING' | 'NOTE' | 'INFO' | 'CONCLUSION';

export interface ParsedStep {
  title: string;
  description: string;
  imageUrl: string;
}
export interface ParsedSection {
  type: SectionType;
  title: string;
  content: string;
  imageUrl: string;
}
export interface ParsedFaq {
  question: string;
  answer: string;
}
export interface ParsedReference {
  refNumber: number;
  title: string;
  url: string;
}
export interface ParsedGuide {
  title: string;
  intro: string;
  metaTitle: string;
  metaDescription: string;
  keywords: string;
  steps: ParsedStep[];
  sections: ParsedSection[];
  faqs: ParsedFaq[];
  references: ParsedReference[];
}

export interface ParseGuideResult {
  result: ParsedGuide | null;
  errors: string[];
  warnings: string[];
}

const SECTION_TYPES = new Set<SectionType>(['TIPS', 'WARNING', 'NOTE', 'INFO', 'CONCLUSION']);
const DIRECTIVE_RE = /^# (TITLE|INTRO|STEP|SECTION|FAQ|REFERENCE|META)\b[ \t]*(.*)$/gm;

function firstLine(body: string): string {
  return body.split('\n')[0] || '';
}

// Decide whether the first line of a body reads like a short heading
// (vs. just being the start of prose). Used when a STEP/SECTION/FAQ
// directive has no inline title and the title must be inferred from the
// first line of the body.
function looksLikeHeading(body: string): boolean {
  const lines = body.split('\n');
  const candidate = (lines[0] || '').trim();
  return (
    candidate.length > 0 &&
    candidate.length <= 80 &&
    !/[.!?]$/.test(candidate)
  );
}

function splitLeadingTitle(body: string): { title: string; rest: string } {
  if (!looksLikeHeading(body)) return { title: '', rest: body.trim() };
  const lines = body.split('\n');
  return { title: lines[0].trim(), rest: lines.slice(1).join('\n').trim() };
}

// If a value is wrapped in markdown link syntax — [label](target) — pull
// out the target (the parenthesized part), since that's the part that's
// always a real URL even when the label is just the same URL repeated,
// some other text, or garbage. If the value isn't a markdown link at
// all, it's returned unchanged.
function unwrapMarkdownLink(value: string): string {
  const m = value.match(/^\[([^\]]*)\]\(([^)]+)\)\s*$/);
  if (m) return m[2].trim();
  return value;
}

function extractImageLine(body: string): { imageUrl: string; rest: string } {
  const m = body.match(/^Image:\s*(\S+)\s*\n?/im);
  if (!m) return { imageUrl: '', rest: body };
  return { imageUrl: m[1].trim(), rest: body.replace(m[0], '').trim() };
}

export function parseGuideText(raw: string): ParseGuideResult {
  const errors: string[] = [];
  const warnings: string[] = [];
  const text = raw.replace(/\r\n/g, '\n').trim();

  if (!text) {
    errors.push('Paste the article text first.');
    return { result: null, errors, warnings };
  }

  const matches = [...text.matchAll(DIRECTIVE_RE)];
  if (matches.length === 0) {
    errors.push('No recognized "# DIRECTIVE" blocks found (# TITLE, # STEP, # SECTION, # FAQ, # REFERENCE…). Check you copied the template format.');
    return { result: null, errors, warnings };
  }

  const blocks: { directive: string; argLine: string; body: string }[] = [];
  for (let i = 0; i < matches.length; i++) {
    const m = matches[i];
    const directive = m[1];
    const argLine = (m[2] || '').trim();
    const start = m.index! + m[0].length;
    const end = i + 1 < matches.length ? matches[i + 1].index! : text.length;
    blocks.push({ directive, argLine, body: text.slice(start, end).trim() });
  }

  const result: ParsedGuide = {
    title: '',
    intro: '',
    metaTitle: '',
    metaDescription: '',
    keywords: '',
    steps: [],
    sections: [],
    faqs: [],
    references: [],
  };

  let refAutoNumber = 1;

  for (const block of blocks) {
    switch (block.directive) {
      case 'TITLE': {
        result.title = (block.argLine || firstLine(block.body)).trim();
        break;
      }
      case 'INTRO': {
        result.intro = block.body.trim();
        break;
      }
      case 'META': {
        for (const line of block.body.split('\n')) {
          const mt = line.match(/^Meta Title:\s*(.*)$/i);
          const md = line.match(/^Meta Description:\s*(.*)$/i);
          const kw = line.match(/^Keywords:\s*(.*)$/i);
          if (mt) result.metaTitle = mt[1].trim();
          else if (md) result.metaDescription = md[1].trim();
          else if (kw) result.keywords = kw[1].trim();
        }
        break;
      }
      case 'STEP': {
        let title = block.argLine;
        let rest = block.body;
        if (!title) {
          // Template always puts the step title on the first line.
          const lines = rest.split('\n');
          title = (lines[0] || '').trim();
          rest = lines.slice(1).join('\n').trim();
        }
        const { imageUrl, rest: rest2 } = extractImageLine(rest);
        if (!title) warnings.push(`A STEP is missing a title (starts: "${firstLine(rest2).slice(0, 40)}…")`);
        result.steps.push({ title: title.trim(), description: rest2, imageUrl });
        break;
      }
      case 'SECTION': {
        const typeMatch = block.argLine.match(/^(\w+)\s*:?\s*(.*)$/);
        let type = (typeMatch ? typeMatch[1].toUpperCase() : 'INFO') as SectionType;
        let title = typeMatch ? typeMatch[2].trim() : '';
        if (!SECTION_TYPES.has(type)) {
          warnings.push(`Unknown section type "${type}" — defaulted to INFO. Use TIPS, WARNING, NOTE, INFO, or CONCLUSION.`);
          type = 'INFO';
        }
        let body = block.body;
        if (!title) {
          const split = splitLeadingTitle(body);
          title = split.title;
          body = split.rest;
        }
        const { imageUrl, rest } = extractImageLine(body);
        result.sections.push({ type, title, content: rest, imageUrl });
        break;
      }
      case 'FAQ': {
        let question = block.argLine;
        let answer = block.body.trim();
        if (!question) {
          question = firstLine(block.body).trim();
          answer = block.body.split('\n').slice(1).join('\n').trim();
        }
        if (!question) warnings.push('A FAQ block is missing a question.');
        if (!answer) warnings.push(`FAQ "${question.slice(0, 40)}" is missing an answer.`);
        result.faqs.push({ question, answer });
        break;
      }
      case 'REFERENCE': {
        let num: number | null = null;
        const numMatch = block.argLine.match(/^(\d+)\s*:?\s*(.*)$/);
        let inlineRest = '';
        if (numMatch) {
          num = parseInt(numMatch[1], 10);
          inlineRest = numMatch[2].trim();
        } else {
          inlineRest = block.argLine.replace(/^:\s*/, '').trim();
        }
        if (!num) num = refAutoNumber;
        refAutoNumber = Math.max(refAutoNumber, num + 1);

        // Preferred format: explicit "Title:" / "URL:" labeled lines in
        // the body (mirrors how STEP already labels "Image:"). This is
        // far more reliable than asking the model to pick a consistent
        // single-line separator between title and url.
        // Note: ChatGPT in particular tends to auto-linkify any URL it
        // writes, so the "URL:" line often comes back wrapped in
        // markdown link syntax itself, e.g.
        //   URL: [https://example.com](https://example.com)
        // (sometimes with the two halves *not* identical). The capture
        // group below greedily takes the whole token; unwrapMarkdownLink
        // then pulls the real address out of it afterward.
        const titleLineMatch = block.body.match(/^Title:\s*(.+)$/im);
        const urlLineMatch = block.body.match(/^URL:\s*(.+?)\s*$/im);

        let title = '';
        let url = '';

        if (titleLineMatch || urlLineMatch) {
          title = unwrapMarkdownLink((titleLineMatch ? titleLineMatch[1] : '').trim());
          url = unwrapMarkdownLink((urlLineMatch ? urlLineMatch[1] : '').trim());
        } else {
          // Fallback for older single-line formats people may still
          // paste in: "# REFERENCE 1: Title | url", markdown links, or
          // a raw url anywhere in the combined argLine+body text.
          const source = (inlineRest + '\n' + block.body).trim();
          const mdLink = source.match(/^\[([^\]]+)\]\((https?:\/\/[^\s)]+)\)/);
          const rawUrlMatch = source.match(/^(.*?)\s*(?:[|\-—:]\s*)?(https?:\/\/\S+)/);
          if (mdLink) {
            title = mdLink[1].trim();
            url = mdLink[2].trim();
          } else if (rawUrlMatch && rawUrlMatch[2]) {
            title = rawUrlMatch[1].replace(/[|\-—:]\s*$/, '').trim();
            url = rawUrlMatch[2].trim();
          } else {
            const pipeIdx = source.indexOf('|');
            title = (pipeIdx === -1 ? source : source.slice(0, pipeIdx)).trim();
          }
        }

        // Strip common trailing punctuation a model might tack onto a
        // URL (periods ending the sentence, closing parens/brackets).
        url = url.replace(/[).,;\]]+$/, '');

        // The LLM sometimes drops the protocol (e.g. "www.kra.go.ke" or
        // "kra.go.ke" instead of "https://kra.go.ke"). The backend's
        // sanitizeUrl() rejects anything that isn't a valid absolute
        // http(s) URL and silently stores an empty string, which makes
        // the reference link point at the current page with no error
        // anywhere. Catch and fix that here, before it ever reaches save.
        if (url && !/^https?:\/\//i.test(url)) {
          const looksLikeDomain = /^[\w-]+(\.[\w-]+)+(\/.*)?$/.test(url);
          if (looksLikeDomain) {
            warnings.push(`Reference [${num}] URL "${url}" was missing "https://" — added automatically. Double-check it resolves correctly.`);
            url = `https://${url}`;
          } else {
            warnings.push(`Reference [${num}] URL "${url}" doesn't look like a valid web address and will be dropped — fix it and re-parse, or edit it directly in the References panel after applying.`);
            url = '';
          }
        }

        if (!url) warnings.push(`Reference [${num}] ("${title.slice(0, 40)}") is missing a URL — format is "# REFERENCE ${num}" then "Title: ..." and "URL: https://..." on their own lines.`);
        if (!title) warnings.push(`Reference [${num}] is missing a title.`);
        result.references.push({ refNumber: num, title, url });
        break;
      }
    }
  }

  // Cross-check: citation markers [n] used in body text should have a
  // matching # REFERENCE block, and vice versa (unused references are
  // fine — just informational, not flagged).
  const definedRefs = new Set(result.references.map(r => r.refNumber));
  const usedRefs = new Set<number>();
  const refUsageRe = /\[(\d+)\]/g;
  const allBodyText = [
    result.intro,
    ...result.steps.map(s => s.description),
    ...result.sections.map(s => s.content),
  ].join('\n');
  let rm: RegExpExecArray | null;
  while ((rm = refUsageRe.exec(allBodyText))) usedRefs.add(parseInt(rm[1], 10));
  for (const used of usedRefs) {
    if (!definedRefs.has(used)) {
      warnings.push(`Citation [${used}] appears in the text but there's no "# REFERENCE ${used}" block defining it.`);
    }
  }

  if (!result.title) warnings.push('No # TITLE block found — the business name default will be used.');
  if (result.steps.length === 0) warnings.push('No # STEP blocks found.');

  return { result, errors, warnings };
}

// ── The prompt to hand to an LLM (Claude, ChatGPT, etc.) ───────────────────
// Kept here so the UI and the parser never drift out of sync.

export const GUIDE_IMPORT_PROMPT = `You are writing a "How to Start a [BUSINESS TYPE] Business in Kenya" guide. Output ONLY plain text in the exact template below — no extra commentary, no markdown code fences.

FORMATTING RULES (used inside any body text):
- **bold** for emphasis
- ## Heading for an H2, ### Heading for an H3, #### Heading for an H4. All headings should be in title case (capitalize each major word).
- - item for bullet list items (one per line, use '-' explicitly for bullet points, not '*' or '•'.) — use to break up dense instructions into clear steps, tips, warnings, etc.However, avoid too many bullet points.
- [link label](https://example.com) for internal links. Check hustlecare.net for relevant content to link to.
- A markdown table: | Col 1 | Col 2 | then | --- | --- | then data rows
- Example table:
| License Type | Cost | Notes |
| --- | --- | --- |
| Single Business Permit | KES 10,000/year | Issued by county government |
| Food Handling License | KES 5,000/year | Required if handling food products |
- To insert a citation anywhere inside a STEP or SECTION body, use:
 [1], [2] etc. to cite a reference inline — every citation number MUST have a matching # REFERENCE block at the end. When adding several citations in one place, do not seperate them with commas (e.g. [1] [2] [3] is correct, [1], [2], [3] is not). Add spaces between citations.
 The citation should be placed immediately after the relevant sentence or phrase, but after the period or any punctuation with space. Example: "The business license costs KES 10,000 per year. [1] " or "The business license costs KES 10,000 per year. [1][2]."
- To insert a callout box anywhere inside a STEP or SECTION body, use:
  :::tips
  Your tip text here.
  :::
  (replace "tips" with warning, note, info, or conclusion as needed)

TEMPLATE TO FILL IN:

# TITLE
How To Start a [BUSINESS TYPE] Business In Kenya

# META
Meta Title: [60 chars max, Title - How To Start a [BUSINESS TYPE] Business In Kenya [Complete Guide]]
Meta Description: [160 chars max]
Keywords: [comma-separated keyword phrases]

# INTRO
[2-4 paragraphs introducing the business opportunity. Cite sources with [1], [2] where relevant. Provide as much data as possible to make the article authoritative, trustworthy resource.]

# STEP
[Step 1 title]
Image: [leave this Image line out entirely if you don't have one]
[Step 1 body — detailed instructions, tips, warnings, etc. in RichTextEditor markdown. Cite sources with [1], [2] where relevant.]

# STEP
[Step 2 title]
[Step 2 body]

[... repeat # STEP for every step in the process. Do not label the steps as "Step 1", "Step 2", etc. ...]

# SECTION TIPS: [optional title, e.g. "Tips for starting a successful [BUSINESS TYPE] business". This can have subheadings or bullet points.] 
[Practical tips content]

# SECTION WARNING: [title - Common Mistakes To Avoid When Starting a [BUSINESS TYPE] Business In Kenya]
[Common mistakes / pitfalls content]

# SECTION CONCLUSION
[Wrap-up — title can be "Conclusion"]

# FAQ
[Question 1]?
[Answer 1]

# FAQ
[Question 2]?
[Answer 2]

[... repeat # FAQ for 4-8 common questions. Note that each QA section should start with # FAQ. Don't label the questions as "Question 1", "Question 2",. 
Don't add citations inside question answers ...Common questions to focus on are around costs, requirements, timelines, profitability, location, etc.]

# REFERENCE 1
Title: [Source title and name]
URL: https://[actual source url]

# REFERENCE 2
Title: [Source name]
URL: https://[actual source url]

[... repeat # REFERENCE for every citation used above, numbered to match the [1] [2] markers in the body text. For the URL, provide the exact naked URL, not markdown link syntax like [Title](url).  ...]

IMPORTANT: Only cite real, plausible sources you're confident exist (government bodies, established organizations). Number references sequentially starting at 1, matching the [1] [2] markers used in the body text. Each reference MUST use exactly this 3-line shape — the directive line, then "Title:" on its own line, then "URL:" on its own line, in that order, with nothing else on either line:
# REFERENCE 1
Title: Exact Source Name
URL: https://exact-url-here.com
Do not combine title and URL on one line, do not use markdown link syntax like [Title](url) for references, and do not add any other text to the Title or URL lines. Every URL MUST start with "https://" or "http://".`;